### PR TITLE
Show lyrics button only if there are lyrics

### PR DESCRIPTION
**Pull request by yazninja**
Hides both drawer and Lyric button while lyrics are not fully loaded.

Preview:
https://user-images.githubusercontent.com/71800112/149300059-06aff898-7d40-4703-988a-82b138370568.mp4

### CODE REVIEW

**Comment by quacksire** [comment]
As we tend to steer towards feature parity in these types of situations, what does Music.app/iTunes do about this?

**Comment by yazninja** [comment]
> As we tend to steer towards feature parity in these types of situations, what does Music.app/iTunes do about this?

Sorry I didn't get this, pls elaborate?

**Comment by quacksire** [comment]
What does the Music app and iTunes (both made by apple) do about songs with no lyrics?

**Comment by yazninja** [comment]
they load then say "No Lyrics Available". I guess this means no...

**Pull request merged**
