### PR TITLE
Added update keybind feature.

### PR DESCRIPTION
**Pull request by Monochromish**
This PR allows users to edit their predetermined key binds.
Works with Darwin platform as well by using Option and Command instead of Control and Shift.
As of now, it only allows users to make a keybind combination of two keys only. In case the Escape key is pressed, it stops recording the keybind.

In this PR, I also:
* Added two new variables to i18n, `settings.notyf.general.keybindings.update.success` and `settings.prompt.general.keybindings.update.success`
* Moved a few key binds from `src/renderer/main/events.js` and added it to the menu bar template

Thank you!

### CODE REVIEW

**Comment by Monochromish** [comment]
@coredev-uk Could you go through it please.

Thank you again.

**Comment by cryptofyre** [comment]
Shoots a ton of Vue warnings, i’d check those out before we merge.

**Review by cryptofyre — CHANGES_REQUESTED** [review]
Fire’s Vue warnings into console over a title directive. Re-test this and fix those before we merge.

**Comment by Monochromish** [comment]
@Amaru8 Fixed the bugs for both sidebar and keybind menu

**Review by Amaru8 — APPROVED** [review]

**Comment by Amaru8** [comment]
The issue has been fixed, I will merge it. Thanks for contributing to **Cider**!

**Pull request merged**
