### PR TITLE
Added create new playlist option to Add To Playlist context menu

### PR DESCRIPTION
**Pull request by Swiftzerr**

### CODE REVIEW

**Comment by Swiftzerr** [comment]
Oops i messed up a few localization things. Wait before pushing.

**Comment by cryptofyre** [comment]
ready?

**Comment by Swiftzerr** [comment]
Still gotta make create new playlist local

**Comment by Swiftzerr** [comment]
I dont really know how I would add a field to localization so someone else would have to do that. Just push it.

**Comment by coredev-uk** [comment]
Use `{{app.getLz('action.createNewPlaylist')}`

**Comment by coredev-uk** [comment]
Is everything else working as you expect?

**Comment by Swiftzerr** [comment]
Havent found anything wrong yet so we good

**Pull request merged**
