### PR TITLE
99.999% i18n coverage for Cider.

### PR DESCRIPTION
**Pull request by maikirakiwi**
**Ready for review**
Done personal testing & debugging

### CODE REVIEW

**Comment by maikirakiwi** [comment]
to i18n translators: Check your appropriate language files as more entries are added to the base file.

**Comment by maikirakiwi** [comment]
Ready for approval & review.

**Comment by maikirakiwi** [comment]
The last 0.001% is due to Unfinished features not getting any i18n as of now because their names might change and everything is too unstable for me to put into the effort of replacing them.

**Comment by gms10ur** [comment]
Hehe nice ratio. Amazing work as always.

**Pull request merged**
