### PR TITLE
Album view: hide tab controls when only one tab exists

### PR DESCRIPTION
**Pull request by pgalhardo**
A small update to the new album view that hides the tab controls when they are not necessary (only one tab exists).

### CODE REVIEW

**Comment by coredev-uk** [comment]
Could you not do a v-if?

**Comment by pgalhardo** [comment]
> Could you not do a v-if?

Using a v-if would hide the entire tab (including the tracklist). The goal here is to only hide the tab controls.

**Comment by quacksire** [comment]
You don’t need to only use v-if on divs

**Comment by pgalhardo** [comment]
Still not sure what you are suggesting here. This uses the `nav-class` property of the bootstrap-vue `b-tabs` component. Actually, will change it to use `nav-wrapper-class` instead, which is a bit more specific.

**Comment by cryptofyre** [comment]
Looks good, ill merge it and see if everything works alright.

**Pull request merged**
