### PR TITLE
UI Changes and Feature Additions

### PR DESCRIPTION
**Pull request by JaxonTekk**
Do not merge yet. WIP PR

- [x] album text styling in fullscreen
- [x] hide album/artist name when hovered over nowPlayingItem on the top
- [x] click on volume button to set volume to 0 and unclick to set volume back to original
- [x] style playback icons

### CODE REVIEW

**Comment by maikirakiwi** [comment]
Looks good for me as of now. Discussed PR w him in VC.

**Comment by cryptofyre** [comment]
ready to rumble yes yes?

**Comment by JaxonTekk** [comment]
yes should be all good

**Comment by cryptofyre** [comment]
bet

**Comment by cryptofyre** [comment]
CONFLICTING FILES AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Pull request merged**
