### PR TITLE
Paginate/infinite scroll for  albums, playlists

### PR DESCRIPTION
**Pull request by kgarner7**
This PR seeks to add infinite scrolling/pagination to the albums tab, as well as playlists (both user-created and album playlists). Pagination/infinite scrolling is now its own component, which emits an event "onRangeChange" to the parent. 

For testing playlist scrolling/pagination, you will probably need a smaller pageSize (e.g., 40).

Albums Paginated
albums (paginated)

Playlist Paginated (set to 40)
playlist-pagination

### CODE REVIEW

**Comment by vapormusic** [comment]
can you move the pagination controls for playlist below the tracks pill

**Comment by kgarner7** [comment]
For every window (library songs, library albums, playlists)?

**Comment by vapormusic** [comment]
> For every window (library songs, library albums, playlists)?

image

**Comment by kgarner7** [comment]
playlists-paged (2)

**Comment by pgalhardo** [comment]
Wouldn't it be better to put the page size somewhere in the settings?

**Review by Zeyzeyno34 — APPROVED** [review]

**Comment by pgalhardo** [comment]
Also, style.css was recently added to .gitignore, don't add it back

**Pull request merged**
