### PR TITLE
Pull request Pre "9 June" Update

### PR DESCRIPTION
**Pull request by mefsaal**
Changes in this PR : Well ........

Update and Change Hardcoded words
Update es_ES to last changes

Sepparate options in menu-label to mac only and other Os's (Linux menubar and Windows not visible but functional).
Now i tested in 3 Oses(Virtual MacOS is shit) and is stable.

Added to Linux and Windows Zoom options 

imagen

I'm open to changes, obviously.

### CODE REVIEW

**Comment by UnbreakCode** [comment]
why u are creating new translations instead of using existing ones? 

for example for "close", you can already use "action.close"

**Comment by mefsaal** [comment]
> why u are creating new translations instead of using existing ones? 
> 
> for example for "close", you can already use "action.close"


Noted, thanks. I do changes later

**Comment by UnbreakCode** [comment]
same btw with reload

**Review by cryptofyre — CHANGES_REQUESTED** [review]
Waiting for the above to be finished, then ill review this.

**Comment by mefsaal** [comment]
Well i found this



```
  "term.accountSettings": "Account Settings",
   "menubar.options.accountsettings": "Account Settings",
   
  "term.about": "About",
    "menubar.options.about": "About",
    
  "term.lyrics": "Lyrics",
    "settings.header.lyrics": "Lyrics",
    
  "term.search": "Search",
    "menubar.options.search": "Search",
      "settings.description.search": "Search",

  "term.listenNow": "Listen Now",
    "menubar.options.listennow": "Listen Now",
      "settings.description.listnow": "Listen Now",
      
  "term.recentlyAdded": "Recently Added",
    "home.recentlyAdded": "Recently Added",
      "menubar.options.recentlyAdded": "Recently Added",
        "settings.description.recentAdd": "Recently Added",
        
  "term.songs": "Songs",
    "menubar.options.songs": "Songs",
      "settings.description.songs": "Songs",
      
  "term.artists": "Artists",
    "menubar.options.artists": "Artists",
          
  "term.albums": "Albums",
    "menubar.options.albums": "Albums",
    
  "term.artists": "Artists",
    "menubar.options.artists": "Artists",
    
  "term.listenNow": "Listen Now",
    "menubar.options.listennow": "Listen Now",
      "settings.description.listnow": "Listen Now",
      
  "term.recentlyAdded": "Recently Added",
    "home.recentlyAdded": "Recently Added",
      "menubar.options.recentlyAdded": "Recently Added",
        "settings.description.recentAdd": "Recently Added",
      
  "term.browse": "Browse",
    "menubar.options.browse": "Browse",
      "settings.description.browse": "Browse",
      
  "settings.description.private": "Toggle Private Session",
    "menubar.options.toggleprivate": "Toggle Private Session",

  "action.showWebRemoteQR": "Web Remote",
   "menubar.options.webremote": "Web Remote",
     "settings.description.remote": "Web Remote",
     
  "term.settings": "Settings",
    "menubar.options.settings": "Settings",
      "settings.description.settings": "Settings",
      
  "term.previous": "Previous",
    "action.tray.previous": "Previous",
      "menubar.options.previous": "Previous",
        "oobe.previous": "Previous",
        
  "term.next": "Next",
    "action.tray.next": "Next",
      "menubar.options.next": "Next",
        "oobe.next": "Next",

  "term.audioSettings": "Audio Settings",
    "menubar.options.audio": "Audio Settings",
      "settings.description.audio": "Audio Settings",
      
  "action.cast.todevices": "Cast to Devices",
    "menubar.options.cast": "Cast To Devices",
      "settings.description.cast": "Cast to Devices",
      
  "menubar.options.zoomin": "Zoom In",
    "settings.description.zoomin": "Zoom In",

  "menubar.options.zoomout": "Zoom Out",
   "settings.description.zoomout": "Zoom Out",
   
  "menubar.options.zoomreset": "Reset Zoom",
   "settings.description.zoomreset": "Reset Zoom",
   
  "action.open": "Open",
   "settings.option.general.keybindings.open": "Open",

```


i need to edit somethings and clear the i18n file and its all

**Comment by pgalhardo** [comment]
Also "action.createPlaylist" ("Create a New Playlist") and "term.createNewPlaylist" ("Create New Playlist").

**Comment by mefsaal** [comment]
> Waiting for the above to be finished, then ill review this.

Hi @cryptofyre  i found some strings to do nothing in the json file, my preference would be to put it in a txt file with the "unused" comment and deleted in the Json main file.

> dialog.cancel
> dialog.ok
> term.applepodcast
> term.itunes
> term.learnMore
> term.enabled
> term.less
> term.funLanguages
> term.check
> term.creditDesignedBy
> home.recentlyAdded
> error.appleMusicSubRequired
> error.connectionError
> action.addToLibrary.error
> action.addToQueue
> action.addToQueue.success
> action.addToQueue.error
> action.removeFromQueue.success
> action.removeFromQueue.error
> action.follow.success
> action.follow.error
> action.unfollow.success
> action.unfollow.error
> action.showInPlaylist
> settings.header.general.description
> settings.option.general.language
> settings.option.general.language.main
> settings.option.general.language.fun
> settings.option.general.language.fun
> settings.notyf.updateCider.update-not-available
> settings.notyf.updateCider.update-downloaded
> settings.notyf.updateCider.update-timeout
> settings.header.audio.description
> settings.header.audio.quality.hireslossless.description
> settings.header.audio.quality.lossless.description
> settings.option.audio.audioLab.subheader
> settings.option.audio.enableAdvancedFunctionality.analogWarmth
> settings.option.audio.enableAdvancedFunctionality.analogWarmth.description
> settings.option.audio.enableAdvancedFunctionality.analogWarmthIntensity
> settings.option.audio.enableAdvancedFunctionality.analogWarmthIntensity.description
> settings.option.audio.enableAdvancedFunctionality.analogWarmthIntensity.smooth
> settings.option.audio.enableAdvancedFunctionality.analogWarmthIntensity.warm
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.NATURAL_STANDARD
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.NATURAL_PLUS
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.E68_1
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.E68_2
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.E168_1
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.Z3600
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.Z8500
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.BSCBM
> settings.option.audio.enableAdvancedFunctionality.atmosphereRealizerMode.CUDDLE
> settings.warn.audio.enableAdvancedFunctionality.ciderPPE.compatibility
> settings.option.audio.enableAdvancedFunctionality.ciderPPEStrength.adaptive
> settings.option.audio.enableAdvancedFunctionality.ciderPPEStrength.legacy
> settings.option.audio.enableAdvancedFunctionality.ciderPPEStrength.aggressive
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.standard
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.soundstage
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.separation
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.minimal
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.audiophile
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.diffused
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.bplk
> settings.option.audio.enableAdvancedFunctionality.tunedAudioSpatialization.profile.hw2k
> settings.warn.audio.enableAdvancedFunctionality.audioSpatialization.compatibility
> settings.header.visual.description
> settings.option.visual.theme.default
> settings.option.visual.theme.dark
> settings.header.window.description
> settings.header.lyrics.description
> settings.header.connectivity.description
> settings.header.experimental.description
> spatial.notTurnedOn
> spatial.spatialProperties
> spatial.width
> spatial.height
> spatial.depth
> spatial.gain
> spatial.roomMaterials
> spatial.roomDimensions
> spatial.roomPositions
> spatial.setDimensions
> spatial.setPositions
> spatial.up
> spatial.front
> spatial.left
> spatial.right
> spatial.back
> spatial.down
> spatial.listener
> spatial.audioSource
> settings.header.unfinished
> remote.web.title
> remote.web.description
> share.platform.twitter.tweet
> share.platform.twitter
> share.platform.facebook
> share.platform.reddit
> share.platform.telegram
> share.platform.whatsapp
> share.platform.messenger
> share.platform.email
> share.platform.songLink
> share.platform.clipboard

**Comment by mefsaal** [comment]
Well, I suppose it's my last changes…. Test it and tell me.

**Review by cryptofyre — APPROVED** [review]
Looks okay.

**Comment by mefsaal** [comment]
> Looks okay.

Well. Merge ?

**Comment by cryptofyre** [comment]
Merging, if this breaks anything ill come after you lol

**Pull request merged**
