### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by EricZhang456**
Some translation are clunky in my opinion. Also translated an untranslated string.

### CODE REVIEW

**Comment by maikirakiwi** [comment]
L104 和 107 我是根据手机app进行翻译的，不知道您PR的版本是否和原文有点出入？

**Comment by vapormusic** [comment]
idk understand pls speak english

**Comment by maikirakiwi** [comment]
> idk understand pls speak english

I was saying that for L104-107 I followed what Apple wrote word for word in their iOS app, I think that’s a translation inaccuracy for this PR.

**Comment by EricZhang456** [comment]
> L104 到 107 我是根据手机app进行翻译的，不知道您PR的版本是否和原文有点出入？

我用的是安卓版的app

**Comment by maikirakiwi** [comment]
OK了解 
可能是因为我手机是繁体中文的原因
我是从台湾繁体转译成简体的 会有些错误

**Pull request merged**
