### PR TITLE
Add color to search button background

### PR DESCRIPTION
**Pull request by Monochromish**
This PR:

* Adds hero color to search button background
* Add hero color to more button background
* Change search button SVG color to gray to match more button SVG

Preview:

image
image

### CODE REVIEW

**Comment by Monochromish** [comment]
Noticed that the follow button is not visible with white hero artwork, will be adding Cider generic shadow to the button

**Comment by Monochromish** [comment]
Not going to add more commits to this pr

**Comment by Monochromish** [comment]
Okay frfr not going to add more commits

**Comment by yazninja** [comment]
nice it works, merging

**Pull request merged**
