### PR TITLE
Pull Request of the day - 25 January 2022

### PR DESCRIPTION
**Pull request by maikirakiwi**
**ready**

### CODE REVIEW

**Comment by maikirakiwi** [comment]
ready to merge
chrome_ZxOylkKMxVmZryuU

**Comment by quacksire** [comment]
i'll wait

**Comment by quacksire** [comment]
11:59

**Comment by maikirakiwi** [comment]
okay just to clarify
I was gonna do web remote 
but I wrote ts interop blah blah blah blah
then got into a rabbit hole full of undefined errors

So I figured
I propose the i18n strings here and let you smarter monkeys do it.

**Pull request merged**
