### PR TITLE
Resolved issue #281

### PR DESCRIPTION
**Pull request by TreeHouseFalcon**
Resolves playlist issue #281

### CODE REVIEW

**Review by coredev-uk — CHANGES_REQUESTED** [review]
Can you update the README in the i18n folder with the new value please

**Comment by TreeHouseFalcon** [comment]
> Can you update the README in the i18n folder with the new value please

Which file is this exactly? The one at `src/i18n/README.md` seems to be mostly generic information about localization. Do you want me to add a comment to the `en_US.jsonc` file itself describing the string?

**Comment by coredev-uk** [comment]
Yeah, the develop branch has it, sorry. Just don't worry.

**Review by coredev-uk — APPROVED** [review]

**Comment by TreeHouseFalcon** [comment]
> Yeah, the develop branch has it, sorry. Just don't worry.

Pushed a small comment to the english locale file anyways. Hope that helps!

**Comment by coredev-uk** [comment]
Thanks.

**Comment by coredev-uk** [comment]
@TreeHouseFalcon You can see what I mean [here](https://github.com/ciderapp/Cider/blob/main/src/i18n/README.md#localization-notices)

**Pull request merged**
