### PR TITLE
Add song.link to discord rpc

### PR DESCRIPTION
**Pull request by scj643**
Add a button in discord's rich presence to song.link

### CODE REVIEW

**Review by cryptofyre — APPROVED** [review]
amogunugusus

**Comment by UnbreakCode** [comment]
I think there should be a switch to enable/disable it

**Comment by scj643** [comment]
> I think there should be a switch to enable/disable it 

If you want to implement it be my guest. I just wanted to get the basic functionality set up.

**Comment by UnbreakCode** [comment]
> > I think there should be a switch to enable/disable it
> 
> If you want to implement it be my guest. I just wanted to get the basic functionality set up.

added! https://github.com/ciderapp/Cider/pull/1435

**Pull request closed without merging**
