### PR TITLE
Update de_DE.jsonc

### PR DESCRIPTION
**Pull request by MarcSteak**
updated German Translation to fit the offical Apple Translation

### CODE REVIEW

**Comment by motz0815** [comment]
could this maybe be merged into development? some of the lines don't exist anymore and were already changed out so just more and more conflicts will arise when this gets merged into main

**Comment by UnbreakCode** [comment]
> could this maybe be merged into development? some of the lines don't exist anymore and were already changed out so just more and more conflicts will arise when this gets merged into main

I really don't know what the problem is to merge that...

**Comment by motz0815** [comment]
> I really don't know what the problem is to merge that...

it's because of merging conflicts later when develop gets merged into main, and there are some changes on main and some changes on develop.
the more recent translations are all on develop, and it's the most up-to-date branch, so it'd be stupid to merge these changes into main

**Comment by UnbreakCode** [comment]
then resolve the merge conflicts and pick the diff from the dev...

**Comment by motz0815** [comment]
...Or just plain do the changes on develop so everyone that uses the development-version also gets the updates and no conflicts will emerge at all?

**Comment by quacksire** [comment]
@UnbreakCode @motz0815 We are using Crowdin for translations. [See here for German](https://crowdin.com/translate/cider-music/10/en-de)

**Pull request closed without merging**
