### PR TITLE
Added translatability to "Open artwork in browser"

### PR DESCRIPTION
**Pull request by Amaru8**

### CODE REVIEW

**Comment by Amaru8** [comment]
it just displays the placeholder, doesnt work.

**Comment by Amaru8** [comment]
done, mergable

**Comment by KillerParticles** [comment]
Not a dev but, would it be possible for the option to open the artwork outside of Cider in a browser? If I open the artwork now it opens inside Cider and not Edge.

**Comment by Amaru8** [comment]
wait what?

it should open in your default browser

**Comment by Amaru8** [comment]
okay, so only the user-uploaded playlist images, and album art will open in a new cider (electron) window

**Pull request closed without merging**
