### PR TITLE
Fix Overlapping items in playback-info/ Resize Queue in fs

### PR DESCRIPTION
**Pull request by yazninja**
it (mostly) does not overlap... Overlaps when app is too small

### CODE REVIEW

**Comment by coredev-uk** [comment]
You could potentially hide elements using `@media only screen and (max-width: )` to handle when the app is too small.

**Comment by yazninja** [comment]
> You could potentially hide elements using `@media only screen and (max-width: )` to handle when the app is too small.

I think there will be no need to do this if the fix in the min-size is fixed

**Comment by yazninja** [comment]
nvm looks like its fixed

**Comment by vapormusic** [comment]
move the js code to index.js please

**Comment by yazninja** [comment]
> move the js code to index.js please

moved

**Review by cryptofyre — APPROVED** [review]
Looks good.

**Pull request merged**
