### PR TITLE
Language: en_SGA + fixed a typo

### PR DESCRIPTION
**Pull request by kyw504100**
SGA: Standard Galactic Alphabet
a.k.a. Minecraft enchanting table language

### CODE REVIEW

**Comment by vapormusic** [comment]
add new added strings please , thanks

**Comment by kyw504100** [comment]
Done

**Comment by kyw504100** [comment]
fixed a typo in spatial-properties.ejs

**Comment by down-bad** [comment]
okay but how many fake languages do we need

**Comment by gms10ur** [comment]
> okay but how many fake languages do we need

they will be separate from main languages like main - fun so dont worry

**Pull request merged**
