### PR TITLE
add recentlyadded view & update sorting function

### PR DESCRIPTION
**Pull request by GGrandma**
- [x] #20

### CODE REVIEW

**Comment by cryptofyre** [comment]
Looks good.

**Review by cryptofyre — APPROVED** [review]

**Comment by GGrandma** [comment]
I have one last commit to fix sorting on the initial library refresh, pushing in a min

**Comment by cryptofyre** [comment]
> I have one last commit to fix sorting on the initial library refresh, pushing in a min

Alrighty

**Comment by vapormusic** [comment]
This view is currently showing recently added albums right?

**Comment by GGrandma** [comment]
It shows the entire library sorted by the date it was added to the library, this includes albums and singles. I think we could remove the dateAdded option from the sortingOptions to avoid the redundancy of the albums page having the exact same options.

**Comment by vapormusic** [comment]
looks alright to me, it will be great if you know how to add playlists to recently added

**Review by vapormusic — APPROVED** [review]

**Comment by GGrandma** [comment]
I looked into adding playlists but I'm not sure how to go about adding that.

**Comment by cryptofyre** [comment]
This considered ready for merge? @GGrandma

**Comment by GGrandma** [comment]
Everything looks good to me, I say yes!

**Pull request merged**
