### PR TITLE
The OCD Update

### PR DESCRIPTION
**Pull request by gms10ur**
### Hello. I've edited the `style.less` file to fix some inconsistent areas in the app.
_Here are a few comparisons;_

**Old playlist to artist transition**
look at the song list starting point and the more (...) button 
playlist-artist-old

**New playlist to artist transition**
playlist-artist-new

**Old to new playlist page**
look at that unused space.... And the old black nav-bar vs new colorful one
playlist-old-vs-new

**Old to new artist page**
the same unused space was here too..
artist-old-new

### OK. Now I want to show you changes related to header.

**Songs page is more uniform around the nav-bar and the header**
Ekran görüntüsü 2022-01-24 002738

**Same with the playlist page too**
Ekran görüntüsü 2022-01-24 002854

**And lastly, the artist page header**
Matched play button theme with the more(...) button too
Ekran görüntüsü 2022-01-24 003025

### Thanks for checking out. I think looks cool. 
_ps. sorry if my css coding is_ `shit`

### CODE REVIEW

**Comment by maikirakiwi** [comment]
I like it

**Comment by coredev-uk** [comment]
Nice PR, the CSS looks great and brings greater consistency to navigation.

**Comment by Swiftzerr** [comment]
bro is dropping awesome prs left and right

**Comment by cryptofyre** [comment]
looks poggers. merged.

**Pull request merged**
