### PR TITLE
Irregular update 01/02

### PR DESCRIPTION
**Pull request by kyw504100**
Task to do:
1. Update the menu with icon ✔️
2. i18n update
3. More?

### CODE REVIEW

**Comment by cryptofyre** [comment]
chad worthy PR.

**Comment by quacksire** [comment]
you ready?

**Comment by Swiftzerr** [comment]
More icons = better. Epic PR

**Comment by kyw504100** [comment]
LoL
actually haven't start working on i18n stuffs
nvm I will open another PR later

**Pull request merged**
