### PR TITLE
[WIP] DiscordRPC - Add Open in Apple Music Button

### PR DESCRIPTION
**Pull request by yazninja**
needs @cryptofyre to add some stuff in cider-preload

### CODE REVIEW

**Comment by vapormusic** [comment]
dont do it like this

**Comment by coredev-uk** [comment]
^^^^

**Review by coredev-uk — CHANGES_REQUESTED** [review]
The attributes parsed into the function already has the URL in them. No need to search.

**Review by coredev-uk — CHANGES_REQUESTED** [review]
You are also going to want to update the URL in the button

**Pull request merged**
