### PR TITLE
BUGFIX: set background color in search hints container

### PR DESCRIPTION
**Pull request by crydotsnake**
Hello 👋🏽 

Is there a specific reason for comment this line out? Because it looks a bit strange like that.

### Before

before

### After

after

### CODE REVIEW

**Comment by Monochromish** [comment]
Can you get rid of the excess portion being colored

**Comment by crydotsnake** [comment]
> Can you get rid of the excess portion being colored

What do you mean?

I think, it looks fine :)

**Comment by Monochromish** [comment]
the square portion outside of the search-hints-container border
instead have only the portion inside being colored

**Comment by crydotsnake** [comment]
> the square portion outside of the search-hints-container border instead have only the portion inside being colored

I see. You mean this.
SCR-20221127-jp7

Will check.

**Comment by Monochromish** [comment]
> I see. You mean this. SCR-20221127-jp7
> 
> Will check.

yeah

**Comment by crydotsnake** [comment]
Is there a way to make changes effect without stop, and start the build everytime?

**Comment by Monochromish** [comment]
`yarn/npm start`

**Comment by crydotsnake** [comment]
SCR-20221127-kjf

What do you think?

**Comment by Swiftzerr** [comment]
Looks good. Merging,

**Pull request merged**
