### PR TITLE
Album/Playlist page search bar improvements

### PR DESCRIPTION
**Pull request by pgalhardo**
This PR attempts to mitigate #1074 by moving the search bar to the body of the playlist. A small button has been added to toggle the visibility of the search bar, which is hidden by default.

Note: the search bar is not fixed at the top of the playlist body (it might become hidden as the user scrolls down). However, clicking on the toggle button will automatically scroll to the search bar, ensuring that it becomes visible when the user needs it.

Search bar hidden:
closed

Search bar visible:
open

### CODE REVIEW

**Comment by Monochromish** [comment]
The search icon needs some touching, I'll be coming up with a commit in some time.

**Comment by pgalhardo** [comment]
> The search icon needs some touching, I'll be coming up with a commit in some time.

Which one? This uses the regular search icon (already used in other places) and proposes an alternative version to be used when the search bar is visible.

**Comment by pgalhardo** [comment]
Added new icon and click animation (thanks to @Monochromish)

**Review by Monochromish — APPROVED** [review]

**Comment by vapormusic** [comment]
Wonderful commit!

**Pull request merged**
