### PR TITLE
Update zh_TW.jsonc

### PR DESCRIPTION
**Pull request by jay900604**
Updated TW language

### CODE REVIEW

**Comment by maikirakiwi** [comment]
"action.tray.quit": "關比"
關閉？

**Review by maikirakiwi — CHANGES_REQUESTED** [review]
"action.tray.quit": "關比" suspected typo

**Comment by jay900604** [comment]
"action.tray.quit": "關閉"  This is correct. thanks!

**Comment by maikirakiwi** [comment]
> "action.tray.quit": "關閉"  This is correct. thanks!

可以重新commit一下更改過的版本嗎？十分感謝。

**Pull request merged**
