### PR TITLE
Paginate songs page

### PR DESCRIPTION
**Pull request by kgarner7**
This seeks to address #1161 (and #1223) by limiting the number of songs that are shown on library-songs at a given time to 250 (one page).
To select which page to view, this adds a page selection below the search/sort bar. It shows a select of (up to) 5 pages, as well as arrows to go to the first/previous/next/last page.

The number 250 was completely arbitrary, maybe it makes sense to have that as an option? My goal was to have as little text as possible.

There are a few changes in `src/renderer/style.css` completely unrelated to me, but I've included that because it was the result of running `yarn start`.

### CODE REVIEW

**Comment by vapormusic** [comment]
infinite scroll may be a better idea, aka load 250 songs first and load the next 250 after scroll

**Comment by kgarner7** [comment]
I decided to try out infinite scrolling (https://github.com/kgarner7/Cider/tree/infinite-scroll), and it works fine until around 7000 songs, at which point I notice that the scrolling becomes somewhat laggy. 
If we have both and let the user choose, that's fine, but at the very least I'm not sure that infinite scroll (or anything where the entire library is shown at once) is always a good idea.

**Comment by vapormusic** [comment]
> I decided to try out infinite scrolling (https://github.com/kgarner7/Cider/tree/infinite-scroll), and it works fine until around 7000 songs, at which point I notice that the scrolling becomes somewhat laggy. If we have both and let the user choose, that's fine, but at the very least I'm not sure that infinite scroll (or anything where the entire library is shown at once) is always a good idea.

Can you check my PR to that branch and test the perf first?

**Comment by kgarner7** [comment]
Unfortunately, I do still see degradation with enough scrolling. Attached are videos of the initial scrolling experience, and the scrolling experience much later on:
 
https://user-images.githubusercontent.com/17521368/176933741-99f0b95e-4a7b-4393-beb0-0e3ed134664f.mp4

https://user-images.githubusercontent.com/17521368/176933829-e3f7ca80-9f98-4513-9ad7-3b6879769b93.mp4

**Comment by cryptofyre** [comment]
Might be a good OOBE dialog setting @booploops

**Comment by kgarner7** [comment]
Added both paging and infinite scrolling! Unfortunately this does require a few additional terms (that are currently untranslated).

Not sure about how to set a default preference based off of another property in the store. I guess you can update the preference on mount?

**Comment by kgarner7** [comment]
Oh, one more thing. When there are enough images loaded (again, somewhere around 7k?), you will run into `net::ERR_INSUFFICIENT_RESOURCES` errors

**Pull request merged**
