### PR TITLE
Add Private Session Toggle to menubar (macOS)

### PR DESCRIPTION
**Pull request by Amaru8**
I also added the keyboard shortcut: `CommandOrControl+Shift+I`

### CODE REVIEW

**Comment by Amaru8** [comment]
it works flawlessly on a Mac

**Comment by yazninja** [comment]
u replaced devtools wtf??

**Comment by Amaru8** [comment]
DevTools is Command+Option+I

**Comment by Amaru8** [comment]
Screenshot

**Comment by coredev-uk** [comment]
That's on mac, on Windows and Linux its Ctrl/Command Shift I

**Pull request merged**
