### PR TITLE
No more HardCoded Strings

### PR DESCRIPTION
**Pull request by mefsaal**
Change string to make a translable word in the JSON file.

PS: if some found another Hardcoded "Strings" tell me and if I can, I changed.

### CODE REVIEW

**Comment by mefsaal** [comment]
unfinished, need more testing.

**Comment by quacksire** [comment]
> menubar.options.about`: Added for `en_US`
  * `menubar.options.settings`: Added for `en_US`
  * `menubar.options.services`: Added for `en_US`
  * `menubar.options.hide`: Added for `en_US`
  * `menubar.options.hideothers`: Added for `en_US`
  * `menubar.options.unhide`: Added for `en_US`
  * `menubar.options.quit`: Added for `en_US`


these are localized by macOS, except settings. any with “role” are too

**Comment by mefsaal** [comment]
> 
> > menubar.options.about`: Added for `en_US`
> 
>     * `menubar.options.settings`: Added for `en_US`
> 
>     * `menubar.options.services`: Added for `en_US`
> 
>     * `menubar.options.hide`: Added for `en_US`
> 
>     * `menubar.options.hideothers`: Added for `en_US`
> 
>     * `menubar.options.unhide`: Added for `en_US`
> 
>     * `menubar.options.quit`: Added for `en_US`
> 
> 
> these are localized by macOS, except settings. any with “role” are too

Yep but on other SO not, i think we separate the function to macOS and others SO

**Comment by quacksire** [comment]
We do not show those menus on other OSes, except on some Linux distro which emulate the macOS handling anyway.

**Comment by mefsaal** [comment]
> We do not show those menus on other OSes, except on some Linux distros which emulate the macOS handling anyway.

I don't use MacOS and dont have anywhere to test, in the function "this.isMac" ( i thing the option to hide if not MacOS ) only have 2 role things " 'front' 'close' ".

```
...(this.isMac ? [
                    {type: 'separator'},
                    {role: 'front'},
                    {role: 'close'},
                ]


```

**Comment by mefsaal** [comment]
Well, I undo changes to string whit MacOS only and let unchanged the string to MacOS/Linux menu.

Tell me if needed something more

**Pull request merged**
