### PR TITLE
Add hero color to the search icon 

### PR DESCRIPTION
**Pull request by Monochromish**
image
image

### CODE REVIEW

**Comment by pgalhardo** [comment]
I suppose this would not be needed if #1189 was merged
Screenshot from 2022-06-26 17-12-01

**Comment by Monochromish** [comment]
> I suppose this would not be needed if #1189 was merged
> 
> Screenshot from 2022-06-26 17-12-01

Truth, but might still look fitting since the Search text on the search bar already changes color based on Background Artwork

**Comment by pgalhardo** [comment]
#1189 moves the search bar to the playlist body so I think you would not have to worry about the text color. Only thing that could need touching is the search icon itself, but that would also apply to the "More" button right next to it I guess. Check the PR if you need more info on how it works, hopefully someones reviews it soon.

**Comment by UnbreakCode** [comment]
> #1189 moves the search bar to the playlist body so I think you would not have to worry about the text color. Only thing that could need touching is the search icon itself, but that would also apply to the "More" button right next to it I guess. Check the PR if you need more info on how it works, hopefully someones reviews it soon.

can there not be conflicts with certain themes?

**Pull request closed without merging**
