### PR TITLE
Flatpak: Repackage deb release instead of building from source

### PR DESCRIPTION
**Pull request by tinywrkb**
For fast tracking Flatpak packaging, this PR suggests using the distributed Debian release as source instead of compiling the app.  
We can switch later to build from source.  
I don't use the app, but a user request this on the Flatpak matrix channel.  
In its current state, this is almost ready for Flathub, it's just missing an appstream appdata/metainfo file.  

Actually, I don't see much point in merging this here. Just take the Flatpak manifest from this PR and submit the app with it to Flathub.

I only tested the stable release, but it looks like Wayland doesn't work, it might need an updated Electron version, so the Wayland socket is disabled.  
MPRIS DBus name seems to be registering correctly, though I haven't tested the player controls are working. If it's broken, then it's likely that `--own-name=org.mpris.MediaPlayer2.Cider.*` permission will fix it.  
I don't use Apple Music, so I haven't tested anything except loading the main UI.  
I wasn't sure about the filesystem permission, so I just allowed access to xdg-music.  

Please note that this repackage the binary deb release and distribute the built app via Flatpak repo, and it's assumed that distribution of the built app is allowed.  
The app's log output during run-time suggests that it uses Widevine, and as long as the lib is not packaged but downloaded during runtime, then it's not a problem.

### CODE REVIEW

**Comment by tinywrkb** [comment]
> I only tested the stable release, but it looks like Wayland doesn't work, it might need an updated Electron version, so the Wayland socket is disabled.

Actually, it's possible that Wayland is working, just not for me. I forgot about [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1279574).

**Comment by rowbawts** [comment]
Thanks again for all the work on this especially so quickly, I am the user from the Matrix that kept bugging the channel until someone helped so again thanks for taking your time for this when no one else would.

**Comment by coredev-uk** [comment]
I can do some testing later today. Thanks.

**Review by coredev-uk — APPROVED** [review]
Great job! This much better than I could ever do. Thanks for this.

**Comment by rowbawts** [comment]
> Great job! This much better than I could ever do. Thanks for this.

I'm glad to see that everything works on your end do you think you'll be able to submit this to Flathub anytime soon so it can be easily installed by anyone using Flatpak?

**Pull request merged**
