### PR TITLE
add rpm package support

### PR DESCRIPTION
**Pull request by LMFuture-Me**

### CODE REVIEW

**Comment by vapormusic** [comment]
It was removed because of long build times

**Comment by LMFuture-Me** [comment]
> It was removed because of long build times

but its not friendly to opensuse or fedora users. at least add it to main branch.

**Comment by cryptofyre** [comment]
An argument can be passed to enable this functionality, not needed especially for other distros that don't need the rpm-tools.

`yarn dist -l rpm`

**Comment by entroxu** [comment]
I need too,Tank you

**Pull request closed without merging**
