### PR TITLE
App Navigation UI Tweak

### PR DESCRIPTION
**Pull request by Monochromish**
This PR displays key bindings for menu item(s) in case they have.

Preview:
boobies

### CODE REVIEW

**Comment by yazninja** [comment]
Wtf is `alt + s` for settings, its always been `ctrl + ,`

**Comment by Monochromish** [comment]
Don't think so, default settings key bindings are `Alt + S`.

**Comment by Monochromish** [comment]
> Wtf is `alt + s` for settings, its always been `ctrl + ,`

Don't think so, default settings key bindings are Alt + S.

**Comment by yazninja** [comment]
> Don't think so, default settings key bindings are Alt + S.
@quacksire xd

**Comment by quacksire** [comment]
> > Don't think so, default settings key bindings are Alt + S.
> > @quacksire xd

These were the default Keybinds for a while before I changed them. We don't have a migration progress for them, so they stick until changed via the keybind manager (or in cider-config)

**Pull request closed without merging**
